using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ListManager : MonoBehaviour
{
    public List<Spell> spellList = new List<Spell>();
    public List<Item> itemList = new List<Item>();
    public List<MonsterStack> monsterList = new List<MonsterStack>();

    // loads lists at startup
    public void LoadLists()
    {
        //mage spells
        spellList.Add(new Spell("Know Location", "DUMAPIC", Spell.Source.none, Spell.Type.mage, Spell.Target.self, 1, "Divine current location", false, true));
        spellList.Add(new Spell("Fire Bolt", "HALITO", Spell.Source.fire, Spell.Type.mage, Spell.Target.enemy, 1, "A small bolt of fire that does 1 - 8 damage", true, false));
        spellList.Add(new Spell("Sleep", "KATINO", Spell.Source.arcane, Spell.Type.mage, Spell.Target.enemy, 1, "A wisp of vapor puts foes to sleep", true, false));
        spellList.Add(new Spell("Mage Shield", "MOGREF", Spell.Source.none, Spell.Type.mage, Spell.Target.self, 1, "A shimmering shield of energy improves AC by 1", true, false));

        spellList.Add(new Spell("Blindness", "DILTO", Spell.Source.none, Spell.Type.mage, Spell.Target.foes, 2, "Darkness hampers the foe's defense", true, false));
        spellList.Add(new Spell("Frost Bolt", "MADITO", Spell.Source.cold, Spell.Type.mage, Spell.Target.enemy, 2, "A small bolt of ice that does 5 - 12 damage", true, false));
        spellList.Add(new Spell("Mage Armor", "SOPIC", Spell.Source.none, Spell.Type.mage, Spell.Target.self, 2, "A shimmering light encases the caster, improving AC by 4", true, false));        

        spellList.Add(new Spell("Lesser Warding", "CORTU", Spell.Source.none, Spell.Type.mage, Spell.Target.party, 3, "A globe of swirling color protects against spells and breath attacks", true, false));
        spellList.Add(new Spell("Spark Bolt", "MOLITO", Spell.Source.lightning, Spell.Type.mage, Spell.Target.enemy, 3, "A small bolt of lightning that does 5 - 12 damage", true, false));
        spellList.Add(new Spell("Heat Wave", "MAHALITO", Spell.Source.fire, Spell.Type.mage, Spell.Target.group, 3, "A blast of heat that does 4 - 24 damage to a group of foes", true, false));
        spellList.Add(new Spell("Cold Front", "MALADITO", Spell.Source.cold, Spell.Type.mage, Spell.Target.group, 3, "A blast of cold that does 4 - 24 damage to a group of foes", true, false));

        spellList.Add(new Spell("Ice Storm", "DALTO", Spell.Source.cold, Spell.Type.mage, Spell.Target.group, 4, "A blast of cold that does 6-36 damage to a group of foes", true, false));
        spellList.Add(new Spell("Flame Storm", "LAHALITO", Spell.Source.fire, Spell.Type.mage, Spell.Target.group, 4, "A blast of fire that does 6-36 damage to a group of foes", true, false));
        spellList.Add(new Spell("Spark Storm", "LAMOLITO", Spell.Source.lightning, Spell.Type.mage, Spell.Target.group, 4, "A blast of lightning that does 6-36 damage to a group of foes", true, false));
        spellList.Add(new Spell("Fear", "MORLIS", Spell.Source.arcane, Spell.Type.mage, Spell.Target.group, 4, "Inflicts FEAR on a group of foes", true, false));

        spellList.Add(new Spell("Blizzard", "MADALTO", Spell.Source.cold, Spell.Type.mage, Spell.Target.group, 5, "Intense cold blast that deals 8-64 damage to a group of foes", true, false));
        spellList.Add(new Spell("Inferno", "MADHALITO", Spell.Source.fire, Spell.Type.mage, Spell.Target.group, 5, "Intense blast of heat that deals 8-64 damage to a group of foes", true, false));
        spellList.Add(new Spell("Chain Spark", "MADMOLITO", Spell.Source.lightning, Spell.Type.mage, Spell.Target.group, 5, "A lightning bolt that deals 8-64 damage to a group of foes", true, false));
        spellList.Add(new Spell("Toxic Cloud", "MAKANTINO", Spell.Source.arcane, Spell.Type.mage, Spell.Target.group, 5, "A cloud of toxin kills a group of foes below level 8", true, false));
        spellList.Add(new Spell("Terror", "MAMORLIS", Spell.Source.arcane, Spell.Type.mage, Spell.Target.foes, 5, "Inflicts FEAR on all who dare oppose the caster", true, false));

        spellList.Add(new Spell("Demon Pact", "HAMAN", Spell.Source.arcane, Spell.Type.mage, Spell.Target.self, 6, "In exchange for a portion of the caster's power, something good happens", true, true));
        spellList.Add(new Spell("Suffocation", "LAKANTINO", Spell.Source.arcane, Spell.Type.mage, Spell.Target.group, 6, "The caster removes air from area of a group of foes, striking them dead", true, false));
        spellList.Add(new Spell("Greater Warding", "MASOPIC", Spell.Source.arcane, Spell.Type.mage, Spell.Target.party, 6, "A globe of swirling color improves the caster's party's AC by 4", true, false));
        spellList.Add(new Spell("Rebuke", "ZILWAN", Spell.Source.arcane, Spell.Type.mage, Spell.Target.enemy, 6, "A bolt of Necrotic Energy destroys an undead being", true, false));
        
        spellList.Add(new Spell("Devil Pact", "MAHAMAN", Spell.Source.arcane, Spell.Type.mage, Spell.Target.self, 7, "In exchange for a portion of the caster's soul, a wish is granted", true, true));
        spellList.Add(new Spell("Teleport", "MALOR", Spell.Source.arcane, Spell.Type.mage, Spell.Target.party, 7, "Teleports party to a new location", true, true));
        spellList.Add(new Spell("Nuke", "TILTOWAIT", Spell.Source.arcane, Spell.Type.mage, Spell.Target.foes, 7, "Intense Power deals 10 - 100 damage to all Foes", true, false));

        
        //priest spell
        spellList.Add(new Spell("Harm", "BADIOS", Spell.Source.divine, Spell.Type.priest, Spell.Target.enemy, 1, "Divine energy strikes a foe for 1 - 8 damage", true, false));
        spellList.Add(new Spell("Heal", "DIOS", Spell.Source.divine, Spell.Type.priest, Spell.Target.friend, 1, "Divine energy heals ally for 1 - 8 health", true, true));
        spellList.Add(new Spell("Bless", "KALKI", Spell.Source.divine, Spell.Type.priest, Spell.Target.party, 1, "Divine energy improves the caster's party's AC by 1 during battle", true, false));
        spellList.Add(new Spell("Light", "MILWA", Spell.Source.divine, Spell.Type.priest, Spell.Target.self, 1, "Divine energy floods the area, brightning it and revealing secret doors, fades after some time", false, true)); //lasts 30 - 41 turns
        spellList.Add(new Spell("Shield", "PORFIC", Spell.Source.divine, Spell.Type.priest, Spell.Target.self, 1, "The caster is wreathed in Divine Energy, improving AC by 4", true, false));

        spellList.Add(new Spell("Reveal Trap", "CALFO", Spell.Source.divine, Spell.Type.priest, Spell.Target.self, 2, "Reveals the truth of a trap", false, false));
        spellList.Add(new Spell("Hold Monster", "MANIFO", Spell.Source.divine, Spell.Type.priest, Spell.Target.group, 2, "Inflicts paralysis on a group of foes", true, false));
        spellList.Add(new Spell("Greater Blessing", "MATU", Spell.Source.divine, Spell.Type.priest, Spell.Target.party, 2, "Divine energy improves the caster's party's AC by 2 during battle", true, false));
        spellList.Add(new Spell("Silence", "MONTINO", Spell.Source.divine, Spell.Type.priest, Spell.Target.group, 2, "Prevents enemy casters from speaking, interrupting their ability to use spells", true, false));

        spellList.Add(new Spell("Prayer", "BAMATU", Spell.Source.divine, Spell.Type.priest, Spell.Target.party, 3, "Improves party's AC by 4 during battle", true, false));
        spellList.Add(new Spell("Cure Paralysis", "DIALKO", Spell.Source.divine, Spell.Type.priest, Spell.Target.friend, 3, "Removes Paralysis from an ally", true, true));
        spellList.Add(new Spell("Identify Monster", "LATUMAPIC", Spell.Source.divine, Spell.Type.priest, Spell.Target.foes, 3, "Identifies Enemies", true, true)); //lasts until exit maze
        spellList.Add(new Spell("Continuous Light", "LOMILWA", Spell.Source.divine, Spell.Type.priest, Spell.Target.party, 3, "Divine energy floods the area, brightning it and revealing secret doors", false, true));
        
        spellList.Add(new Spell("Greater Harm", "BADIAL", Spell.Source.divine, Spell.Type.priest, Spell.Target.enemy, 4, "Inflicts 2-16 damage on a foe", true, false));
        spellList.Add(new Spell("Greater Heal", "DIAL", Spell.Source.divine, Spell.Type.priest, Spell.Target.friend, 4, "Heals ally for 2 - 16 health", true, true));
        spellList.Add(new Spell("Cure Poison", "LATUMOFIS", Spell.Source.divine, Spell.Type.priest, Spell.Target.friend, 4, "Removes Poison from an ally", true, true));
        spellList.Add(new Spell("Greater Shield", "MAPORFIC", Spell.Source.divine, Spell.Type.priest, Spell.Target.party, 4, "Continous Shield lowers Party's AC by 2", true, true)); //lasts until exit maze

        spellList.Add(new Spell("Death Touch", "BADI", Spell.Source.divine, Spell.Type.priest, Spell.Target.enemy, 5, "Divine Fury strikes a foe dead", true, false));
        spellList.Add(new Spell("Max Harm", "BADIALMA", Spell.Source.divine, Spell.Type.priest, Spell.Target.enemy, 5, "Inflicts 3 - 24 damage on a foe", true, false));
        spellList.Add(new Spell("Life Touch", "DI", Spell.Source.divine, Spell.Type.priest, Spell.Target.friend, 5, "Appeals to the Heavens to restores a fallen ally to life", true, true));
        spellList.Add(new Spell("Flame Tower", "LITOKAN", Spell.Source.fire, Spell.Type.priest, Spell.Target.group, 5, "A tower of divine flame inflicts 3 - 24 damage on a group of enemies", true, false));
        spellList.Add(new Spell("Max Heal", "DIALMA", Spell.Source.divine, Spell.Type.priest, Spell.Target.friend, 5, "Heals an Ally's health by 3 - 24", true, true));

        spellList.Add(new Spell("Spirit Recall", "LOKTOFEIT", Spell.Source.divine, Spell.Type.priest, Spell.Target.party, 6, "The party is transported back to town, but without their worldly possesions", true, true));
        spellList.Add(new Spell("Dancing Blades", "LORTO", Spell.Source.divine, Spell.Type.priest, Spell.Target.group, 6, "Manifests blades that sping into a group of foes, dealing 6-36 damage", true, false));
        spellList.Add(new Spell("Critical Harm", "MABADI", Spell.Source.divine, Spell.Type.priest, Spell.Target.enemy, 6, "Smites the unrepentant, leaving them with only a shadow of their former health", true, false));
        spellList.Add(new Spell("Divine Favor", "MADI", Spell.Source.divine, Spell.Type.priest, Spell.Target.party, 6, "The Heavens smile upon the party, fully restoring everyone who still lives", true, true));

        spellList.Add(new Spell("Resurrection", "KADORTO", Spell.Source.divine, Spell.Type.priest, Spell.Target.friend, 7, "Restores the dead to life", true, true));
        spellList.Add(new Spell("Word_Death", "MALIKTO", Spell.Source.divine, Spell.Type.priest, Spell.Target.foes, 7, "The sound of a forbidden Divine Word strikes all foes for 12 - 72 damage", true, false));

        //Items        (FMPTBSLN)
        itemList.Add(new Item(0, "debris", Item.Type.Misc, "a bit of junk", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(1, "Long Sword", Item.Type.Sword, "A sword with a long blade.", -1, 15, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 4, 1, 8, 0));
        itemList.Add(new Item(2, "Broad Sword", Item.Type.Sword, "A sword with a blade that is thick and heavy.", -1, 15, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 4, 2, 8, 0));
        itemList.Add(new Item(3, "Short Sword", Item.Type.Sword, "A sword with a heavy hilt and stubby blade", -1, 10, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 3, 1, 6, 0));
        itemList.Add(new Item(4, "Hatchet", Item.Type.Axe, "A short, heavy axe.", -1, 5, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTLN", 0, 3, 1, 4, 0));
        itemList.Add(new Item(5, "Maul", Item.Type.Axe, "A long haft with a crude but heavy axe head.", -1, 10, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FL", 0, 4, 1, 6, 0));
        itemList.Add(new Item(6, "Battle Axe", Item.Type.Axe, "A one-handed axe with a broad cutting head.", -1, 15, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FL", 0, 4, 1, 8, 0));
        itemList.Add(new Item(7, "Double Axe", Item.Type.Axe, "A one-handed axe with two broad cutting heads.", -1, 20, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FL", 0, 4, 2, 8, 0));
        itemList.Add(new Item(8, "Dagger", Item.Type.Dagger, "A solid fighting dagger.", -1, 5, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 5, 1, 4, 0));
        itemList.Add(new Item(9, "Kukri", Item.Type.Dagger, "A dagger with a longer blade, curved forward.", -1, 10, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 6, 1, 6, 0));
        itemList.Add(new Item(10, "Sabre", Item.Type.Dagger, "A heavy hilt with a broad, curved blade.", -1, 15, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 6, 2, 6, 0));
        itemList.Add(new Item(11, "Club", Item.Type.Mace, "A stout bashing weapon, reinforced with iron bands.", -1, 5, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTBLN", 0, 1, 1, 3, 0));
        itemList.Add(new Item(12, "Mace", Item.Type.Mace, "A mace with an iron head.", -1, 10, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPBLN", 0, 2, 2, 6, 0));
        itemList.Add(new Item(13, "Flail", Item.Type.Mace, "A spiked striking head attached to the hilt by a chain.", -1, 15, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPBLN", 0, 3, 1, 7, 0));
        itemList.Add(new Item(14, "Staff", Item.Type.Staff, "Walking stick or weapon? Both.", -1, 5, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 0, 0, 1, 5, 0));
        itemList.Add(new Item(15, "Robe", Item.Type.Armor, "Cloth robes, reinforced with thick pads.", -1, 15, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 1));
        itemList.Add(new Item(16, "Small Shield", Item.Type.Shield, "A small shield that buckles onto your arm.", -1, 20, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTSLN", 1));
        itemList.Add(new Item(17, "Round Shield", Item.Type.Shield, "A medium circular shield.", -1, 30, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 2));
        itemList.Add(new Item(18, "Large Shield", Item.Type.Shield, "A large, kite-shaped shield.", -1, 40, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSL", 4));
        itemList.Add(new Item(19, "Leather Armor", Item.Type.Armor, "Sturdy boiled leather with reinforced buckles.", -1, 50, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTBSLN", 2));
        itemList.Add(new Item(20, "Chain Mail", Item.Type.Armor, "Sturdy interlocked iron links.", -1, 90, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 3));
        itemList.Add(new Item(21, "Breast Plate", Item.Type.Armor, "A solid iron plate, reinforced with chain.", -1, 200, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 4));
        itemList.Add(new Item(22, "Plate Mail", Item.Type.Armor, "Interlocked iron plates, reinforced with mail.", -1, 750, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 5));
        itemList.Add(new Item(23, "Cap", Item.Type.Helm, "A leather cap.", -1, 90, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 1));
        itemList.Add(new Item(24, "Helm", Item.Type.Helm, "An iron cap.", 0, 100, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSL", 2));
        itemList.Add(new Item(25, "Great Helm", Item.Type.Helm, "An iron cap with a visor.", 0, 125, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSL", 3));
        itemList.Add(new Item(26, "Heal Potion", Item.Type.Potion, "A glass vial filled with red liquid.", -1, 500, Item.Protection.None, false, "Heal", "Heal", 0));
        itemList.Add(new Item(27, "Cure Potion", Item.Type.Potion, "A glass vial filled with green liquid.", -1, 500, Item.Protection.None, false, "Cure Poison", "Cure Poison", 0));
        itemList.Add(new Item(28, "Long Sword +1", Item.Type.Sword, "An exquisite sword with a long blade.", 0, 1400, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 5, 2, 9, 2));
        itemList.Add(new Item(29, "Broad Sword +1", Item.Type.Sword, "An exquisite sword with a blade that is thick and heavy.", 0, 1400, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 5, 3, 9, 0));
        itemList.Add(new Item(30, "Short Sword +1", Item.Type.Sword, "An exquisite sword with a heavy hilt and stubby blade", 2, 1000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 4, 2, 7, 2));
        itemList.Add(new Item(31, "Battle Axe +1", Item.Type.Axe, "An exquisite one-handed axe with a broad cutting head.", 0, 1500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FL", 0, 5, 2, 9, 0));
        itemList.Add(new Item(32, "Double Axe +1", Item.Type.Axe, "An exquisite one-handed axe with two broad cutting heads.", 0, 1700, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FL", 0, 5, 3, 9, 0));
        itemList.Add(new Item(33, "Dagger +1", Item.Type.Dagger, "An exquisite fighting dagger.", 0, 900, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 6, 2, 5, 2));
        itemList.Add(new Item(34, "Kukri +1", Item.Type.Dagger, "An exquisite dagger with a longer blade, curved forward.", 0, 950, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 7, 2, 7, 2));
        itemList.Add(new Item(35, "Club +1", Item.Type.Mace, "An exquisite stout bashing weapon, reinforced with steel bands.", 0, 700, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTBLN", 0, 2, 2, 4, 2));
        itemList.Add(new Item(36, "Mace +1", Item.Type.Mace, "An exquisite mace with an steel head.", 0, 1250, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPBLN", 0, 3, 3, 7, 2));
        itemList.Add(new Item(37, "Staff_Mogref", Item.Type.Staff, "This gnarled staff glows softly.", 0, 3000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 0, 1, 1, 6, 0));
        itemList.Add(new Item(38, "Scroll_Sleep", Item.Type.Scroll, "This scroll is labeled 'KANTINO'", 0, 300, Item.Protection.None, false, "", "Sleep", 0));
        itemList.Add(new Item(39, "Leather Armor +1", Item.Type.Armor, "Leather armor with steel studs.", -1, 1500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTBSLN", 3));
        itemList.Add(new Item(40, "Chain Mail +1", Item.Type.Armor, "Sturdy interlocked steel links.", -1, 1500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 4));
        itemList.Add(new Item(41, "Breast Plate +1", Item.Type.Armor, "A solid steel plate, reinforced with interlocked rings.", -1, 1500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 5));
        itemList.Add(new Item(42, "Plate Mail +1", Item.Type.Armor, "Interlocked steel plates, reinforced with mail.", 1, 1500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 6));
        itemList.Add(new Item(43, "Shield +1", Item.Type.Shield, "This shield is lightweight, but sturdy.", -1, 1500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTSLN", 4));
        itemList.Add(new Item(44, "Scroll_Harm", Item.Type.Scroll, "This scroll is labeled 'BADIOS'", -1, 500, Item.Protection.None, false, "", "Harm", 0));
        itemList.Add(new Item(45, "Scroll_Fire Bolt", Item.Type.Scroll, "This scroll is labeled 'HALITO'", 25, 500, Item.Protection.None, false, "", "Fire Bolt", 0));
        itemList.Add(new Item(46, "Long Sword -1", Item.Type.Sword, "This sword is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FSLN", 0, 1, 1, 8, 1));
        itemList.Add(new Item(47, "Broad Sword -1", Item.Type.Sword, "This sword is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FSLN", 0, 1, 2, 8, 1));
        itemList.Add(new Item(48, "Short Sword -1", Item.Type.Sword, "This sword is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 1, 1, 6, 1));
        itemList.Add(new Item(49, "Battle Axe -1", Item.Type.Axe, "This axe is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FL", 0, 1, 1, 8, 1));
        itemList.Add(new Item(50, "Double Axe -1", Item.Type.Axe, "This axe is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FL", 0, 1, 2, 8, 1));
        itemList.Add(new Item(51, "Dagger -1", Item.Type.Dagger, "This dagger is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 1, 1, 4, 1));
        itemList.Add(new Item(52, "Kukri -1", Item.Type.Dagger, "This kukri is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 1, 1, 6, 1));
        itemList.Add(new Item(53, "Club -1", Item.Type.Mace, "This club is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPTBLN", 0, 1, 1, 3, 1));
        itemList.Add(new Item(54, "Mace -1", Item.Type.Mace, "This mace is cursed, and it hates you.", 0, 1000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPBLN", 0, 1, 2, 6, 1));
        itemList.Add(new Item(55, "Staff +2", Item.Type.Staff, "This iron staff glows softly.", 1, 2500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 2, 1, 3, 6, 0));
        itemList.Add(new Item(56, "Dragon Slayer", Item.Type.Sword, "Long sword with a Dragon Motif etched into the blade.", 0, 10000, Item.Protection.Dragon, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 4, 2, 11, 0));
        itemList.Add(new Item(57, "Cap +1", Item.Type.Helm, "A tooled leather cap.", 0, 2500, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 2));
        itemList.Add(new Item(58, "Helm +1", Item.Type.Helm, "A steel cap.", 0, 3000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSL", 3));
        itemList.Add(new Item(59, "Great Helm +1", Item.Type.Helm, "A steel cap with a faceplate.", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSL", 4));
        itemList.Add(new Item(60, "Leather Armor -1", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 100, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPTBSLN", 1));
        itemList.Add(new Item(61, "Chain Mail -1", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 1500, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPSLN", 1));
        itemList.Add(new Item(62, "Breast Plate -1", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 1500, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPSLN", 1));
        itemList.Add(new Item(63, "Plate Mail -1", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 1500, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FSLN", 1));
        itemList.Add(new Item(64, "Shield -1", Item.Type.Shield, "This shield is cursed and it hates you.", 0, 1500, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPTSLN", 1));
        itemList.Add(new Item(65, "Gem Amulet", Item.Type.Amulet, "Amulet inscripton reads: 'No matter where you go, there you are.'", 0, 5000, Item.Protection.None, false, "Know Location", "", 0));
        itemList.Add(new Item(66, "Scroll_Harm", Item.Type.Scroll, "This scroll is labeled 'BADIOS'", 0, 500, Item.Protection.None, false, "", "Harm", 0));
        itemList.Add(new Item(67, "Armor Potion", Item.Type.Potion, "A glass vial filled with red liquid.", 0, 500, Item.Protection.None, false, "", "Mage Armor", 0));
        itemList.Add(new Item(68, "Long Sword +2", Item.Type.Sword, "An enchanted sword with a long blade.", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 6, 3, 12, 3));
        itemList.Add(new Item(69, "Broad Sword +2", Item.Type.Sword, "An enchanted sword with a blade that is thick and heavy.", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 6, 3, 10, 3));
        itemList.Add(new Item(70, "Short Sword +2", Item.Type.Sword, "An enchanted sword with a heavy hilt and stubby blade", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 5, 3, 8, 3));
        itemList.Add(new Item(71, "Battle Axe +2", Item.Type.Axe, "An enchanted one-handed axe with a broad cutting head.", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FL", 0, 6, 3, 10, 2));
        itemList.Add(new Item(72, "Double Axe +2", Item.Type.Axe, "An enchanted one-handed axe with two broad cutting heads.", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FL", 0, 6, 4, 10, 2));
        itemList.Add(new Item(73, "Club +2", Item.Type.Mace, "An enchanted stout bashing weapon, reinforced with golden bands.", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTBLN", 0, 3, 3, 8, 2));
        itemList.Add(new Item(74, "Mace +2", Item.Type.Mace, "An enchanted mace with an golden head.", 0, 4000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPBLN", 0, 4, 3, 10, 2));
        itemList.Add(new Item(75, "Scroll_Continuous Light", Item.Type.Scroll, "This scroll is labeled 'LOMILWA'", 0, 2500, Item.Protection.None, false, "Continuous Light", "", 0));
        itemList.Add(new Item(76, "Scroll_Blindness", Item.Type.Scroll, "This scroll is labeled 'DILTO'", 0, 2500, Item.Protection.None, false, "", "Blindness", 0));
        itemList.Add(new Item(77, "Bronze Gauntlets", Item.Type.Gloves, "These gautlets are made with bronze plates.", -1, 6000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 1));
        itemList.Add(new Item(78, "Leather Armor +2", Item.Type.Armor, "Enchanted Leather armor with gold studs.", 0, 6000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTBSLN", 4));
        itemList.Add(new Item(79, "Chain Mail +2", Item.Type.Armor, "Enchanted armor with interlocked gold links.", 0, 6000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 5));
        itemList.Add(new Item(80, "Plate Mail +2", Item.Type.Armor, "Interlocked enchanted gold plate armor, reinforced with mail.", 0, 6000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 7));
        itemList.Add(new Item(81, "Shield +2", Item.Type.Shield, "This enchanted shield longs to stop enemy blows.", 0, 6000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTSLN", 5));
        itemList.Add(new Item(82, "Helm +2 (evil)", Item.Type.Helm, "An steel cap.", 0, 8000, Item.Protection.None, false, "", "Harm", 0, Item.Alignment.Evil, "FPSL", 4));
        itemList.Add(new Item(83, "Great Helm +2 (evil)", Item.Type.Helm, "An steel cap with a faceplate.", 0, 8000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FSL", 5));
        itemList.Add(new Item(84, "Greater Heal Potion", Item.Type.Potion, "A glass vial filled with bright blue liquid.", 0, 5000, Item.Protection.None, false, "Greater Heal", "Greater Heal", 0));
        itemList.Add(new Item(85, "Ring_Shield", Item.Type.Ring, "This ring has a shield engraved on it.", 0, 10000, Item.Protection.None, false, "", "Shield", 0));
        itemList.Add(new Item(86, "Were Slayer", Item.Type.Sword, "An ornate long sword with various wild beasts etched into the blade.", 0, 10000, Item.Protection.Were, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 5, 2, 11, 2));
        itemList.Add(new Item(87, "Mage Masher", Item.Type.Sword, "An ugly short sword with unreadable runes etched into the blade.", 0, 10000, Item.Protection.Mage, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 5, 2, 7, 2));
        itemList.Add(new Item(88, "Mace_Purity", Item.Type.Mace, "Engraved on this enchanted mace is the word 'LATUMOFIS'.", 0, 10000, Item.Protection.Insect, false, "Cure Poison", "Cure Poison", 0, Item.Alignment.Any, "FPBLN", 0, 3, 1, 8, 2));
        itemList.Add(new Item(89, "Staff_Montino", Item.Type.Staff, "This staff is capped with a blue gem.", 0, 15000, Item.Protection.None, false, "", "Silence", 0, Item.Alignment.Any, "FMPTBSLN", 0, 1, 2, 6, 0));
        itemList.Add(new Item(90, "Blade_Cuisinart", Item.Type.Sword, "Legend has it that the famous blacksmith 'Cuisinart' forged 20 of these swords.", 0, 15000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 0, 6, 10, 13, 4));                
        itemList.Add(new Item(91, "Amulet_Hold Monster", Item.Type.Amulet, "On this amulet is an etching of a monster in a cage.", 0, 15000, Item.Protection.None, false, "", "Hold Monster", 0));
        itemList.Add(new Item(92, "Rod_Flame", Item.Type.Rod, "This rod is warm to the touch", 0, 25000, Item.Protection.None, false, "", "Heat Wave", 0, Item.Alignment.Any, "MBS", 0, 0, 1, 1, 0));
        itemList.Add(new Item(93, "Rod_Ice", Item.Type.Rod, "This rod is cold to the touch", 0, 25000, Item.Protection.None, false, "", "Cold Front", 0, Item.Alignment.Any, "MBS", 0, 0, 1, 1, 0));
        itemList.Add(new Item(94, "Evil Mail +2", Item.Type.Armor, "Black Enchanted chain mail reinforced with spikes.", 0, 8000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FPSLN", 5));
        itemList.Add(new Item(95, "Nuetral Plate Mail +2", Item.Type.Armor, "This armor is flat grey in color, and is inscibed with an image of balancing scales.", 0, 8000, Item.Protection.None, false, "", "", 0, Item.Alignment.Neutral, "FSLN", 7));
        itemList.Add(new Item(96, "Evil Shield +3", Item.Type.Shield, "This enchanted shield is black and covered in spikes.", 0, 25000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FPTSLN", 6));
        itemList.Add(new Item(97, "Amulet_Toxins", Item.Type.Amulet, "On this amulet is inscribed 'MAKANITO'.", 0, 20000, Item.Protection.None, false, "", "Toxic Cloud", 0));
        itemList.Add(new Item(98, "Helm_Malor", Item.Type.Helm, "An iron cap with a crown carved into it.", 0, 25000, Item.Protection.None, false, "Teleport", "Teleport", 0, Item.Alignment.Any, "FMPTBSLN", 2));
        itemList.Add(new Item(99, "Scroll_Greater Harm", Item.Type.Scroll, "This scroll is labeled 'BADIAL'", 0, 8000, Item.Protection.None, false, "", "Greater Harm", 0));
        itemList.Add(new Item(100, "Short Sword -2", Item.Type.Sword, "This cursed sword has a history of murder and betrayal. It hates you.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 2, 1, 4, 1));
        itemList.Add(new Item(101, "Dagger +2", Item.Type.Dagger, "An enchanted fighting dagger.", 0, 8000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 3, 3, 6, 3));
        itemList.Add(new Item(102, "Kukri +2", Item.Type.Dagger, "An enchanted dagger with a longer blade, curved forward.", 0, 8000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 0, 3, 3, 8, 3));
        itemList.Add(new Item(103, "Club -2", Item.Type.Mace, "This club is cursed, and it wants you dead.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPTBLN", 0, 2, 1, 1, 1));
        itemList.Add(new Item(104, "Mace -2", Item.Type.Mace, "This mace is cursed, and it wants you dead.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPBLN", 0, 2, 1, 4, 1));
        itemList.Add(new Item(105, "Staff -2", Item.Type.Mace, "This staff is cursed, and it wants you dead.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 0, 2, 1, 4, 1));
        itemList.Add(new Item(106, "Dagger_Speed", Item.Type.Dagger, "This dagger vibrates with speed and desire to do harm to foes.", 0, 30000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FTSLN", 3, 5, 1, 4, 7));
        itemList.Add(new Item(107, "Cursed Robe", Item.Type.Armor, "This cursed robe hates you, wants you dead. It snaps at you with teeth.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FMPTBSLN", 1));
        itemList.Add(new Item(108, "Leather Armor -2", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPTBSLN", 2));
        itemList.Add(new Item(109, "Chain Mail -2", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPSLN", 2));
        itemList.Add(new Item(110, "Breast Plate -2", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPSLN", 2));
        itemList.Add(new Item(111, "Plate Mail -2", Item.Type.Armor, "This armor is cursed and it hates you.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FSLN", 2));
        itemList.Add(new Item(112, "Shield -2", Item.Type.Shield, "This shield is cursed and it hates you.", 0, 8000, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPTSLN", 2));
        itemList.Add(new Item(113, "Cursed Helm", Item.Type.Helm, "This helm is cursed and it hates you.", 0, 800, Item.Protection.None, true, "", "", 0, Item.Alignment.Any, "FPSL", 1));
        itemList.Add(new Item(114, "Breast Plate +2", Item.Type.Armor, "Enchanted gold plate armor, reinforced with interlocked rings.", 0, 10000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 6));
        itemList.Add(new Item(115, "Silver Gauntlets", Item.Type.Gloves, "These gautlets are made with enchanted silver plates.", 0, 60000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FSLN", 3));
        itemList.Add(new Item(116, "Evil Long Sword +3", Item.Type.Sword, "A black sword with a long blade and an evil aura.", 0, 50000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FSLN", 0, 7, 4, 14, 4));
        itemList.Add(new Item(117, "Evil Broad Sword +3", Item.Type.Sword, "A black broad sword with an evil aura.", 0, 50000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FSLN", 0, 5, 5, 14, 4));
        itemList.Add(new Item(118, "Evil Short Sword +3", Item.Type.Sword, "A black short sword with an evil aura.", 0, 50000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FTSLN", 0, 6, 4, 9, 4));
        itemList.Add(new Item(119, "Evil Battle Axe +3", Item.Type.Axe, "A black one-bladed battle axe with an evil aura.", 0, 50000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FL", 0, 6, 3, 10, 4));
        itemList.Add(new Item(120, "Evil Double Axe +3", Item.Type.Axe, "A black two-bladed battle axe with an evil aura.", 0, 50000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FL", 0, 6, 4, 10, 4));
        itemList.Add(new Item(121, "Dagger_Thieves", Item.Type.Dagger, "This dagger tingles in your hand and the shadows invite you inside.", 0, 50000, Item.Protection.Thief, false, "BECOME NINJA", "", 0, Item.Alignment.Evil, "TN", 0, 5, 1, 6, 4));
        itemList.Add(new Item(122, "Breast Plate +3", Item.Type.Armor, "Enchanted platnium plate armor, reinforced with interlocked rings.", 0, 100000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPSLN", 7));
        itemList.Add(new Item(123, "Lords Garb", Item.Type.Armor, "Enchanted platnium plate armor, reinforced with interlocked rings.", 0, 1000000, Item.Protection.Dragon, false, "Divine Favor", "", 1, Item.Alignment.Any, "L", 10));
        itemList.Add(new Item(124, "Muramasa Blade", Item.Type.Sword, "Once drawn, the Muramasa blade MUST taste blood before it is returned to its scabbard.", 0, 1000000, Item.Protection.None, false, "INCREASE STENGTH", "", 0, Item.Alignment.Any, "S", 0, 7, 10, 50, 3));
        itemList.Add(new Item(125, "Shuriken", Item.Type.Sword, "When thrown, this enchanted shuriken returns to the wielder.", 0, 500000, Item.Protection.Thief, false, "INCREASE MAX HEALTH", "", 0, Item.Alignment.Evil, "N", 0, 7, 11, 15, 3));
        itemList.Add(new Item(126, "Chain Mail +3", Item.Type.Armor, "Enchanted armor with interlocked platnium links.", 0, 15000, Item.Protection.Dragon, false, "", "", 0, Item.Alignment.Any, "FPSLN", 6));
        itemList.Add(new Item(127, "Evil Plate Mail +3", Item.Type.Armor, "This armor is blackend and is covered in spikes.", 0, 150000, Item.Protection.None, false, "", "", 0, Item.Alignment.Evil, "FPSLN", 9));
        itemList.Add(new Item(128, "Good Plate Mail +3", Item.Type.Armor, "This armor is made from platnium and glows softly.", 0, 150000, Item.Protection.None, false, "", "", 0, Item.Alignment.Good, "FPSLN", 9));
        itemList.Add(new Item(129, "Shield +3", Item.Type.Shield, "This enchanted shield glows softly.", 0, 25000, Item.Protection.None, false, "", "", 0, Item.Alignment.Any, "FPTSLN", 6));
        itemList.Add(new Item(130, "Ring_Healing", Item.Type.Ring, "This ring is plain, but it tingles with life as you hold it.", 0, 30000, Item.Protection.None, false, "", "", 1));
        itemList.Add(new Item(131, "Ring_Prot(Undead)", Item.Type.Ring, "This ring is plain and topped with a silver skull.", 0, 50000, Item.Protection.Undead, false, "", "", 0));
        itemList.Add(new Item(132, "Ring_Prot(Demons)", Item.Type.Ring, "This ring is plain and topped with a silver smirking demon.", 0, 50000, Item.Protection.Demon, false, "", "", 0));
        itemList.Add(new Item(133, "Ring_Prot(Animals)", Item.Type.Ring, "This ring is plain and topped with a silver beast.", 0, 50000, Item.Protection.Animal, false, "", "", 0));
        itemList.Add(new Item(134, "Ring_Death", Item.Type.Ring, "This ring is plain, but it saps warmth from you as you hold it.", 0, 50000, Item.Protection.None, true, "", "", -1));
        itemList.Add(new Item(135, "Werdna's Amulet", Item.Type.Amulet, "Werdna's Cursed Amulet!", 0, 214748360, Item.Protection.None, true, "Divine Favor", "Teleport", 0));

        //Keys
        itemList.Add(new Item(136, "Bear Figurine", Item.Type.Key, "A small statue of a strange looking bear wearing a floppy hat and a scarf.", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(137, "Frog Figurine", Item.Type.Key, "A small statue of a strange looking frog with googly eyes and a neck frill.", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(138, "Bronze Key", Item.Type.Key, "A large key made of bronze.", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(139, "Silver Key", Item.Type.Key, "A large key made of silver.", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(140, "Gold Key", Item.Type.Key, "A large key made of gold.", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(141, "Blue Ribbon", Item.Type.Key, "this ribbon is blue, tied into a bow, and has '1st Place' printed on it.", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(142, "Triangle Key", Item.Type.Key, "A large key with a triangle inscribed on it", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(143, "Square Key", Item.Type.Key, "A large key with a square inscribed on it", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(144, "Pentagonal Key", Item.Type.Key, "A large key with a pentagon inscribed on it", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(145, "Hexagonal Key", Item.Type.Key, "A large key with a hexagon inscribed on it", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(146, "Heptogonal Key", Item.Type.Key, "A large key with a heptagon inscribed on it", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(147, "Octagonal Key", Item.Type.Key, "A large key with an octagon inscribed on it", 0, 0, Item.Protection.None, false, "", "", 0));
        itemList.Add(new Item(148, "Nonagonal Key", Item.Type.Key, "A large key with a nonagon inscribed on it", 0, 0, Item.Protection.None, false, "", "", 0));

        //Monsters
        int i;
        i = 00; monsterList.Add(new MonsterStack(i, "SLIME", "SLIMES", "BUBBLY SLIME", "BUBBLY SLIMES", 2, 4, 1, 3, 1, MonsterStack.Class.Animal, 12, 0, 0, 0, 55, 0, 10, "physical arcane", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 1, 0 });
        i = 01; monsterList.Add(new MonsterStack(i, "SMALL HUMANOID", "SMALL HUMANOIDS", "ORC", "ORCS", 3, 6, 1, 4, 0, MonsterStack.Class.Fighter, 10, 0, 0, 0, 235, 0, 10, "fire", "sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 02; monsterList.Add(new MonsterStack(i, "SMALL HUMANOID", "SMALL HUMANOIDS", "KOBOLD", "KOBOLDS", 3, 7, 2, 3, 1, MonsterStack.Class.Fighter, 8, 0, 0, 0, 415, 0, 10, "physical cold", "sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 2, 1, 1, 2, 1 });
        i = 03; monsterList.Add(new MonsterStack(i, "SKELETON", "SKELETONS", "UNDEAD KOBOLD", "UNDEAD KOBOLDS", 2, 7, 2, 3, 2, MonsterStack.Class.Undead, 10, 0, 0, 0, 230, 0, 10, "fire cold", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 1 });
        i = 04; monsterList.Add(new MonsterStack(i, "SCRUFFY MAN", "SCRUFFY MEN", "ROGUE", "ROGUES", 2, 5, 2, 5, 1, MonsterStack.Class.Thief, 10, 0, 0, 0, 380, 0, 10, "", "sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 4, 0, 2, 2, 1 });
        i = 05; monsterList.Add(new MonsterStack(i, "SCRUFFY MAN", "SCRUFFY MEN", "BUSHWHACKER", "BUSHWHACKERS", 2, 5, 3, 6, 1, MonsterStack.Class.Fighter, 8, 0, 0, 0, 620, 0, 10, "", "sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 6, 1, 2, 4, 1 });
        i = 06; monsterList.Add(new MonsterStack(i, "MAN IN CHAIN", "MEN IN CHAIN", "HIGHWAYMAN", "HIGHWAYMEN", 2, 12, 3, 4, 2, MonsterStack.Class.Fighter, 6, 0, 0, 0, 840, 0, 10, "", "crit sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[12] { 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1 });
        i = 07; monsterList.Add(new MonsterStack(i, "WEIRD HUMANOID", "WEIRD HUMANOIDS", "ZOMBIE", "ZOMBIES", 2, 7, 1, 10, 1, MonsterStack.Class.Undead, 4, 0, 0, 0, 520, 0, 10, "", "para", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 6, 0 });
        i = 08; monsterList.Add(new MonsterStack(i, "SLIME", "SLIMES", "CREEPING CRUD", "CREEPING CRUDS", 2, 7, 3, 4, 0, MonsterStack.Class.Animal, 6, 0, 0, 0, 550, 0, 10, "cold arcane", "poison", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 3, 1 });
        i = 09; monsterList.Add(new MonsterStack(i, "GAS CLOUD", "GAS CLOUDS", "GAS CLOUD", "GAS CLOUDS", 2, 8, 2, 4, 0, MonsterStack.Class.Mythical, 10, 0, 0, 0, 350, 0, 10, "", "para run", 2, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 10; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "LVL1 MAGE", "LVL1 MAGES", 1, 1, 1, 4, 1, MonsterStack.Class.Mage, 4, 0, 0, 0, 475, 1, 11, "", "sleep run",1,0,0)); monsterList[i].SetAttacks(new int[3] { 2, 2, 0 });
        i = 11; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "LVL1 PRIEST", "LVL1 PRIESTS", 1, 4, 1, 8, 0, MonsterStack.Class.Priest, 5, 0, 0, 0, 515, 1, 11, "", "sleep run",0,1,0)); monsterList[i].SetAttacks(new int[3] { 1, 8, 0 });
        i = 12; monsterList.Add(new MonsterStack(i, "SMALL OBJECT", "SMALL OBJECTS", "CREEPING COIN?", "CREEPING COINS?", 9, 9, 1, 1, 0, MonsterStack.Class.Mythical, 4, 1, 0, 0, 920, 2, 4, "fire cold poison", "call", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 1, 0 });
        i = 13; monsterList.Add(new MonsterStack(i, "MAN IN KIMONO", "MEN IN KIMONOS", "LVL1 NINJA", "LVL1 NINJAS", 2, 8, 2, 4, 2, MonsterStack.Class.Fighter, 5, 0, 0, 0, 600, 1, 11, "", "crit sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 4, 0, 1, 4, 0, 1, 4, 0 });
        i = 14; monsterList.Add(new MonsterStack(i, "RABBIT", "RABBITS", "VORPAL BUNNY", "VORPAL BUNNIES", 4, 8, 3, 6, 2, MonsterStack.Class.Animal, 6, 0, 0, 0, 735, 1, 11, "cold", "crit run", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 6, 0, 1, 8, 0 });
        i = 15; monsterList.Add(new MonsterStack(i, "GIANT RODENT", "GIANT RODENTS", "CAPYBARA", "CAPYBARAS", 3, 9, 4, 4, 0, MonsterStack.Class.Animal, 8, 0, 0, 0, 520, 1, 11, "", "poison run", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 10, 0 });
        i = 16; monsterList.Add(new MonsterStack(i, "AMPHIBIAN", "AMPHIBIANS", "GIANT TOAD", "GIANT TOADS", 6, 8, 4, 5, 0, MonsterStack.Class.Animal, 7, 0, 0, 0, 795, 1, 11, "fire", "poison run", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 4, 0, 1, 6, 0, 2, 3, 2 });
        i = 17; monsterList.Add(new MonsterStack(i, "MANGY DOG", "MANGY DOGS", "COYOTE", "COYOTES", 4, 8, 4, 6, 0, MonsterStack.Class.Animal, 8, 0, 0, 0, 780, 1, 11, "", "run", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 4, 4, 0 });
        i = 18; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "LVL3 PRIEST", "LVL3 PRIESTS", 5, 7, 3, 8, 1, MonsterStack.Class.Priest, 4, 0, 0, 0, 990, 1, 11, "", "poison sleep run", 0, 2, 0)); monsterList[i].SetAttacks(new int[3] { 1, 8, 2 });
        i = 19; monsterList.Add(new MonsterStack(i, "MAN IN KIMONO", "MEN IN KIMONOS", "LVL3 SAMURAI", "LVL3 SAMURAI", 4, 8, 3, 6, 1, MonsterStack.Class.Fighter, 5, 0, 0, 0, 795, 1, 11, "", "run", 1, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 4, 1, 1, 6, 1, 1, 4, 1 });
        i = 20; monsterList.Add(new MonsterStack(i, "MAN IN KIMONO", "MEN IN KIMONOS", "LVL3 NINJA", "LVL3 NINJA", 4, 10, 3, 8, 0, MonsterStack.Class.Fighter, 3, 0, 0, 0, 1360, 2, 12, "", "poison crit", 0, 0, 0)); monsterList[i].SetAttacks(new int[15] { 1, 4, 0, 1, 4, 0, 1, 4, 0, 1, 4, 0, 1, 4, 0 });
        i = 21; monsterList.Add(new MonsterStack(i, "BEAR", "BEARS", "WERE BEAR", "WERE BEARS", 4, 8, 5, 8, 0, MonsterStack.Class.Were, 2, 0, 0, 1, 1320, 2, 12, "cold", "poison para run", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 3, 6, 1 }); 
        i = 22; monsterList.Add(new MonsterStack(i, "FLY", "FLIES", "DRAGON FLY", "DRAGON FLIES", 2, 4, 2, 8, 0, MonsterStack.Class.Dragon, 4, 1, 0, 0, 1275, 2, 12, "fire", "sleep", 0, 0, 20)); monsterList[i].SetAttacks(new int[9] { 1, 4, 0, 1, 4, 0, 1, 6, 0 }); 
        i = 23; monsterList.Add(new MonsterStack(i, "WEIRD HUMANOID", "WEIRD HUMANOIDS", "ROTTING CORPSE", "ROTTING CORPSES", 1, 5, 2, 8, 0, MonsterStack.Class.Undead, 6, 0, 0, 0, 680, 2, 12, "", "para", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 3, 0, 1, 3, 0, 1, 6, 0 });
        i = 24; monsterList.Add(new MonsterStack(i, "OGRE", "OGRES", "OGRE", "OGRES", 1, 8, 4, 8, 1, MonsterStack.Class.Fighter, 5, 0, 0, 0, 960, 2, 12, "", "sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 2, 6, 0 });
        i = 25; monsterList.Add(new MonsterStack(i, "INSECT", "INSECTS", "HUGE SPIDER", "HUGE SPIDERS", 1, 8, 2, 8, 2, MonsterStack.Class.Insect, 6, 0, 0, 0, 600, 2, 12, "", "poison sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 6, 0 });
        i = 26; monsterList.Add(new MonsterStack(i, "GIANT RODENT", "GIANT RODENTS", "WERERAT", "WERERATS", 1, 4, 3, 8, 1, MonsterStack.Class.Were, 6, 0, 0, 0, 755, 2, 12, "arcane", "sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 8, 0 });
        i = 27; monsterList.Add(new MonsterStack(i, "INSECT", "INSECTS", "BORING BEETLE", "BORING BEETLES", 1, 8, 5, 8, 0, MonsterStack.Class.Insect, 3, 0, 0, 0, 1120, 2, 12, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 5, 4, 0 });
        i = 28; monsterList.Add(new MonsterStack(i, "DRAGON", "DRAGONS", "GAS DRAGON", "GAS DRAGONS", 1, 4, 1, 4, 0, MonsterStack.Class.Dragon, 3, 1, 0, 0, 2075, 2, 12, "", "", 1, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 4, 0, 1, 4, 0, 3, 6, 0 });
        i = 29; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "PRESTESS", "PRIESTESSES", 1, 6, 3, 8, 1, MonsterStack.Class.Priest, 4, 0, 0, 0, 870, 2, 12, "", "sleep", 0, 2, 0)); monsterList[i].SetAttacks(new int[3] { 1, 6, 2 });
        i = 30; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ARMOR", "SWORDSMAN", "SWORDSMEN", 1, 4, 2, 10, 0, MonsterStack.Class.Fighter, 3, 0, 0, 0, 960, 3, 13, "", "sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 2, 7, 0 });
        i = 31; monsterList.Add(new MonsterStack(i, "INSECT", "INSECTS", "HUGE SPIDER", "HUGE SPIDERS", 1, 8, 2, 8, 2, MonsterStack.Class.Insect, 6, 0, 0, 0, 600, 3, 13, "", "poison sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 6, 0 });
        i = 32; monsterList.Add(new MonsterStack(i, "ANIMAL", "ANIMALS", "ATTACK DOG", "ATTACK DOGS", 1, 6, 4, 8, 0, MonsterStack.Class.Animal, 1, 0, 0, 0, 1120, 3, 13, "", "sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 6, 0 });
        i = 33; monsterList.Add(new MonsterStack(i, "GARGOYLE", "GARGOYLES", "GARGOYLE", "GARGOYLES", 1, 6, 4, 8, 4, MonsterStack.Class.Mythical, 5, 0, 0, 0, 2435, 3, 13, "arcane", "", 0, 0, 50)); monsterList[i].SetAttacks(new int[12] { 1, 3, 0, 1, 3, 0, 1, 6, 0, 1, 4, 0 });
        i = 34; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "GRAVE MIST", "GRAVE MISTS", 1, 6, 4, 8, 0, MonsterStack.Class.Undead, 4, 0, 0, 0, 1080, 3, 13, "", "para", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 4, 0, 1, 4, 0, 1, 8, 0 });
        i = 35; monsterList.Add(new MonsterStack(i, "ANIMAL", "ANIMALS", "DRAGON PUPPY", "DRAGON PUPPIES", 1, 6, 5, 10, 0, MonsterStack.Class.Dragon, 4, 1, 0, 0, 2280, 3, 13, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 10, 0 });
        i = 36; monsterList.Add(new MonsterStack(i, "WOLF", "WOLVES", "WEREWOLF", "WEREWOLVES", 1, 6, 4, 8, 3, MonsterStack.Class.Were, 5, 0, 0, 0, 975, 3, 13, "arcane", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 2, 4, 0, 2, 4, 0 });
        i = 37; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "SHADE", "SHADES", 1, 6, 3, 8, 3, MonsterStack.Class.Undead, 7, 0, 1, 0, 875, 3, 13, "arcane", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 1 });
        i = 38; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "BISHOP", "BISHOPS", 1, 6, 4, 8, 0, MonsterStack.Class.Priest, 4, 0, 0, 0, 1135, 3, 13, "", "sleep", 1, 4, 0)); monsterList[i].SetAttacks(new int[3] { 1, 10, 0 });
        i = 39; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ARMOR", "MINOR DAIMYO", "MINOR DAIMYOS", 1, 6, 4, 10, 0, MonsterStack.Class.Fighter, 2, 0, 0, 0, 1200, 3, 13, "", "sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 12, 0 });
        i = 40; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "LVL5 MAGE", "LVL5 MAGES", 1, 6, 5, 4, 0, MonsterStack.Class.Mage, 10, 0, 0, 0, 620, 4, 14, "", "sleep", 3, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 41; monsterList.Add(new MonsterStack(i, "MAN IN LEATHER", "MEN IN LEATHER", "LVL4 THIEF", "LVL4 THIEVES", 1, 6, 4, 8, 3, MonsterStack.Class.Thief, 10, 0, 0, 0, 740, 4, 14, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 6, 0, 2, 6, 0 });
        i = 42; monsterList.Add(new MonsterStack(i, "ANIMAL", "ANIMALS", "KILLER WOLF", "KILLER WOLVES", 1, 6, 6, 8, 0, MonsterStack.Class.Animal, 0, 0, 0, 0, 1460, 4, 14, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 2, 4, 0, 2, 4, 0 });
        i = 43; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "SPIRIT", "SPIRITS", 1, 6, 7, 3, 2, MonsterStack.Class.Mythical, 2, 0, 0, 1, 1245, 4, 14, "arcane", "poison", 3, 0, 25)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 44; monsterList.Add(new MonsterStack(i, "INSECT", "INSECTS", "GIANT SPIDER", "GIANT SPIDERS", 1, 6, 4, 8, 4, MonsterStack.Class.Insect, 4, 0, 0, 0, 960, 4, 14, "", "poison", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 2, 4, 0 });
        i = 45; monsterList.Add(new MonsterStack(i, "ANIMAL", "ANIMALS", "WERETIGER", "WERETIGERS", 1, 8, 5, 8, 0, MonsterStack.Class.Were, 4, 0, 0, 1, 1405, 4, 14, "arcane", "poison sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 2, 6, 0, 2, 6, 0, 1, 4, 0 });
        i = 46; monsterList.Add(new MonsterStack(i, "STRANGE ANIMAL", "STRANGE ANIMALS", "MEDUSA LIZARD", "MEDUSA LIZARDS", 1, 6, 5, 8, 0, MonsterStack.Class.Mythical, 6, 0, 0, 0, 1040, 4, 14, "", "stone", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 3, 0 });
        i = 47; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "LVL5 PRIEST", "LVL5 PRIESTS", 1, 5, 5, 8, 0, MonsterStack.Class.Priest, 4, 0, 0, 0, 1220, 4, 14, "", "", 0, 3, 0)); monsterList[i].SetAttacks(new int[3] { 1, 6, 2 });
        i = 48; monsterList.Add(new MonsterStack(i, "MAN IN BLACK", "MEN IN BLACK", "LVL6 NINJA", "LVL6 NINJAS", 1, 5, 6, 10, 0, MonsterStack.Class.Fighter, 6, 0, 0, 0, 1520, 4, 14, "", "", 4, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 6, 0, 1, 6, 0, 1, 6, 0 });
        i = 49; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "LVL7 MAGE", "LVL7 MAGES", 1, 6, 7, 4, 0, MonsterStack.Class.Mage, 8, 0, 0, 0, 1000, 4, 14, "", "sleep", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 50; monsterList.Add(new MonsterStack(i, "MAN IN LEATHER", "MEN IN LEATHER", "MASTER THIEF", "MASTER THIEVES", 1, 6, 4, 6, 0, MonsterStack.Class.Thief, 4, 0, 0, 0, 960, 5, 15, "", "sleep run", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 6, 0, 1, 6, 0, 2, 6, 0 });
        i = 51; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ARMOR", "MAJOR DAIMYO", "MAJOR DAIMYOS", 1, 5, 7, 12, 0, MonsterStack.Class.Fighter, 0, 0, 0, 0, 2340, 5, 15, "", "", 0, 0, 20)); monsterList[i].SetAttacks(new int[6] { 1, 10, 0, 1, 4, 0 });
        i = 52; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "HIGH PRIEST", "HIGH PRIESTS", 1, 6, 8, 8, 0, MonsterStack.Class.Priest, 3, 0, 0, 0, 2160, 5, 15, "", "", 0, 5, 0)); monsterList[i].SetAttacks(new int[3] { 1, 8, 2 });
        i = 53; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ARMOR", "CHAMPION SAMURAI", "CHAMPION SAMURAI", 1, 6, 10, 10, 0, MonsterStack.Class.Fighter, 2, 0, 0, 0, 2395, 5, 15, "", "", 1, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 12, 2 });
        i = 54; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "ARCH MAGE", "ARCH MAGES", 1, 6, 8, 4, 2, MonsterStack.Class.Mage, 9, 0, 0, 0, 790, 5, 15, "", "", 2, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 55; monsterList.Add(new MonsterStack(i, "MAN IN LEATHER", "MEN IN LEATHER", "MASTER THIEF", "MASTER THEIVES", 1, 6, 6, 6, 0, MonsterStack.Class.Thief, 3, 0, 0, 0, 1140, 5, 15, "", "run", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 8, 0, 3, 8, 0 });
        i = 56; monsterList.Add(new MonsterStack(i, "STRANGE ANIMAL", "STRANGE ANIMALS", "GAZE HOUND", "GAZE HOUNDS", 1, 5, 4, 8, 0, MonsterStack.Class.Animal, -1, 0, 0, 0, 1235, 5, 15, "arcane", "para run", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 2, 0 });
        i = 57; monsterList.Add(new MonsterStack(i, "OGRE", "OGRES", "OGRE LORD", "OGRE LORDS", 1, 5, 8, 8, 0, MonsterStack.Class.Mage, 4, 0, 0, 1, 1790, 5, 15, "", "", 3, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 12, 0 });
        i = 58; monsterList.Add(new MonsterStack(i, "STRANGE HUMANOID", "STRANGE HUMANOIDS", "TROLL", "TROLLS", 1, 3, 6, 8, 6, MonsterStack.Class.Fighter, 4, 0, 0, 3, 1720, 5, 15, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 4, 4, 1, 4, 4, 1, 4, 4 });
        i = 59; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "LIFE STEALER", "LIFE STEALERS", 1, 1, 5, 8, 3, MonsterStack.Class.Undead, 3, 0, 2, 0, 2240, 5, 15, "arcane", "", 3, 3, 20)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 60; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "NIGHT STALKER", "NIGHT STALKERS", 2, 6, 5, 8, 3, MonsterStack.Class.Undead, 4, 0, 1, 0, 1475, 6, 16, "arcane", "", 0, 0, 25)); monsterList[i].SetAttacks(new int[3] { 1, 6, 0 });
        i = 61; monsterList.Add(new MonsterStack(i, "STRANGE ANIMAL", "STRANGE ANIMALS", "WYVERN", "WYVERNS", 1, 6, 7, 8, 7, MonsterStack.Class.Animal, 3, 0, 0, 0, 1540, 6, 16, "", "poison", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 2, 8, 0, 1, 6, 0 });
        i = 62; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "LVL8 PRIEST", "LVL8 PRIESTS", 1, 5, 7, 8, 0, MonsterStack.Class.Priest, 3, 0, 0, 0, 1720, 6, 16, "", "", 0, 4, 0)); monsterList[i].SetAttacks(new int[3] { 1, 8, 0 });
        i = 63; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ARMOR", "LVL10 FIGHTER", "LVL10 FIGHTERS", 1, 6, 7, 10, 0, MonsterStack.Class.Fighter, 0, 0, 0, 0, 1900, 6, 16, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 12, 0, 1, 12, 0 });
        i = 64; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "LVL7 MAGE", "LVL7 MAGES", 1, 5, 7, 4, 0, MonsterStack.Class.Mage, 8, 0, 0, 0, 1240, 6, 16, "", "", 5, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 65; monsterList.Add(new MonsterStack(i, "MAN IN LEATHER", "MEN IN LEATHER", "LVL7 THIEF", "LVL7 THIEVES", 1, 5, 7, 6, 0, MonsterStack.Class.Thief, 4, 0, 0, 0, 1220, 6, 16, "", "run", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 8, 0, 3, 8, 0 });
        i = 66; monsterList.Add(new MonsterStack(i, "MONK", "MONKS", "LVL8 NINJA", "LVL8 NINJAS", 1, 3, 8, 4, 0, MonsterStack.Class.Fighter, 4, 0, 0, 0, 1020, 6, 16, "", "crit", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 2, 6, 0, 1, 6, 0 });
        i = 67; monsterList.Add(new MonsterStack(i, "GIANT", "GIANTS", "EARTH GIANT", "EARTH GIANTS", 1, 5, 1, 1, 40, MonsterStack.Class.Giant, 9, 0, 0, 0, 20435, 6, 16, "arcane", "", 0, 0, 85)); monsterList[i].SetAttacks(new int[6] { 2, 8, 0, 2, 8, 0 });
        i = 68; monsterList.Add(new MonsterStack(i, "DEMON", "DEMONS", "LESSER DEMON", "LESSER DEMONS", 1, 1, 10, 8, 0, MonsterStack.Class.Demon, 4, 0, 0, 0, 5100, 6, 16, "", "call", 0, 0, 60)); monsterList[i].SetAttacks(new int[15] { 2, 6, 0, 2, 6, 0, 1, 3, 0, 1, 3, 0, 1, 4, 4 });
        i = 69; monsterList.Add(new MonsterStack(i, "STRANGE ANIMAL", "STRANGE ANIMALS", "CHIMERA", "CHIMERAS", 1, 4, 9, 6, 0, MonsterStack.Class.Animal, 2, 1, 0, 0, 3515, 6, 16, "fire", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[18] { 1, 3, 0, 1, 3, 0, 1, 4, 0, 1, 4, 0, 2, 4, 0, 3, 4, 0 });
        i = 70; monsterList.Add(new MonsterStack(i, "GIANT", "GIANTS", "FIRE GIANT", "FIRE GIANTS", 1, 4, 11, 8, 4, MonsterStack.Class.Giant, 3, 0, 0, 0, 2115, 7, 17, "fire", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 5, 6, 0 }); 
        i = 71; monsterList.Add(new MonsterStack(i, "STRANGE ANIMAL", "STRANGE ANIMALS", "GORGON", "GORGONS", 1, 1, 8, 8, 0, MonsterStack.Class.Mythical, 2, 1, 0, 0, 2920, 7, 17, "", "stone", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 2, 6, 0 });
        i = 72; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "LVL8 BISHOP", "LVL8 BISHOPS", 1, 6, 8, 8, 0, MonsterStack.Class.Priest, 2, 0, 0, 0, 2060, 7, 17, "", "", 3, 4, 0)); monsterList[i].SetAttacks(new int[3] { 2, 6, 0 });
        i = 73; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ARMOR", "LVL8 FIGHTER", "LVL8 FIGHTERS", 1, 6, 8, 10, 0, MonsterStack.Class.Fighter, -1, 0, 0, 0, 2140, 7, 17, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 12, 2, 1, 12, 2 });
        i = 74; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "LVL10 MAGE", "LVL10 MAGES", 1, 6, 10, 4, 0, MonsterStack.Class.Mage, 10, 0, 0, 0, 1400, 7, 17, "", "", 5, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 75; monsterList.Add(new MonsterStack(i, "MAN IN LEATHER", "MEN IN LEATHER", "THIEF", "THIEVES", 1, 5, 9, 6, 0, MonsterStack.Class.Thief, 4, 0, 0, 0, 1640, 7, 17, "", "run", 0, 0, 0)); monsterList[i].SetAttacks(new int[12] { 1, 8, 0, 1, 3, 0, 3, 8, 0, 2, 10, 0 });
        i = 76; monsterList.Add(new MonsterStack(i, "MAN IN ROBE", "MEN IN ROBES", "MASTER NINJA", "MASTER NINJAS", 1, 5, 10, 4, 0, MonsterStack.Class.Fighter, 3, 0, 0, 0, 1280, 7, 17, "", "crit", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 10, 3, 1, 10, 3, 1, 10, 3 });
        i = 77; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "MURPHY'S GHOST", "MURPHY'S GHOSTS", 1, 1, 10, 10, 10, MonsterStack.Class.Undead, -3, 0, 0, 1, 4450, 3, 3, "fire cold arcane", "sleep", 0, 0, 40)); monsterList[i].SetAttacks(new int[3] { 1, 1, 1 });
        i = 78; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "WILL O' WISP", "WILL O' WISPS", 1, 2, 10, 8, 0, MonsterStack.Class.Mythical, -8, 0, 0, 0, 42840, 7, 17, "physical fire cold arcane", "", 0, 0, 95)); monsterList[i].SetAttacks(new int[3] { 2, 8, 0 });
        i = 79; monsterList.Add(new MonsterStack(i, "STRANGE ANIMAL", "STRANGE ANIMALS", "BLEEB", "BLEEBS", 1, 8, 10, 8, 0, MonsterStack.Class.Animal, 0, 0, 0, 0, 3300, 8, 18, "physical fire cold arcane", "run call", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 8, 1, 1, 8, 1 });
        i = 80; monsterList.Add(new MonsterStack(i, "GIANT", "GIANTS", "FROST GIANT", "FROST GIANTS", 1, 4, 1, 8, 50, MonsterStack.Class.Giant, 6, 0, 0, 0, 40875, 8, 18, "cold", "", 0, 0, 95)); monsterList[i].SetAttacks(new int[3] { 3, 10, 0 });
        i = 81; monsterList.Add(new MonsterStack(i, "DRAGON", "DRAGONS", "FIRE DRAGON", "FIRE DRAGONS", 1, 4, 12, 8, 0, MonsterStack.Class.Dragon, -1, 1, 0, 0, 5000, 8, 18, "fire", "", 5, 0, 0)); monsterList[i].SetAttacks(new int[9] { 1, 4, 0, 1, 4, 0, 4, 4, 0 });
        i = 82; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "HIGH PRIEST", "HIGH PRIESTS", 1, 1, 11, 8, 0, MonsterStack.Class.Priest, 2, 0, 0, 0, 3300, 8, 18, "", "", 0, 6, 0)); monsterList[i].SetAttacks(new int[6] { 1, 8, 0, 1, 8, 0 });
        i = 83; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "HIGH WIZARD", "HIGH WIZARDS", 1, 1, 12, 4, 0, MonsterStack.Class.Mage, 4, 0, 0, 0, 2395, 8, 18, "fire", "", 6, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 84; monsterList.Add(new MonsterStack(i, "MAN IN LEATHER", "MEN IN LEATHER", "MASTER THIEF", "MASTER THIEVES", 1, 1, 12, 6, 0, MonsterStack.Class.Thief, 2, 0, 0, 0, 1935, 8, 18, "", "run", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 8, 0, 5, 8, 0 });
        i = 85; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "HATAMOTO", "HATAMOTOS", 1, 1, 12, 4, 0, MonsterStack.Class.Fighter, -1, 0, 0, 0, 1600, 8, 18, "", "crit", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 3, 8, 0, 3, 8, 0, 3, 8, 0 });
        i = 86; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "VAMPIRE", "VAMPIRES", 1, 4, 11, 8, 0, MonsterStack.Class.Undead, -1, 0, 2, 1, 3330, 8, 18, "", "para", 3, 0, 20)); monsterList[i].SetAttacks(new int[9] { 2, 8, 0, 1, 4, 0, 1, 4, 0 });
        i = 87; monsterList.Add(new MonsterStack(i, "DEMON", "DEMONS", "GREATER DEMON", "GREATER DEMONS", 1, 6, 11, 8, 0, MonsterStack.Class.Demon, -3, 0, 0, 1, 44090, 8, 18, "", "poison para call", 5, 0, 95)); monsterList[i].SetAttacks(new int[15] { 2, 12, 0, 1, 6, 0, 1, 4, 0, 1, 4, 0, 1, 4, 0 });
        i = 88; monsterList.Add(new MonsterStack(i, "GIANT", "GIANTS", "POISON GIANT", "POISON GIANTS", 1, 4, 1, 1, 80, MonsterStack.Class.Giant, 3, 0, 0, 0, 40840, 8, 18, "", "poison", 0, 0, 95)); monsterList[i].SetAttacks(new int[3] { 4, 10, 0 });
        i = 89; monsterList.Add(new MonsterStack(i, "DRAGON", "DRAGONS", "DRAGON ZOMBIE", "DRAGON ZOMBIES", 1, 4, 12, 8, 0, MonsterStack.Class.Undead, -2, 1, 0, 0, 5200, 8, 18, "", "", 5, 0, 25)); monsterList[i].SetAttacks(new int[9] { 1, 8, 0, 1, 8, 0, 3, 12, 0 });
        i = 90; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ARMOR", "RAVER LORD", "RAVER LORDS", 1, 1, 15, 10, 0, MonsterStack.Class.Animal, 10, 0, 0, 2, 4155, 9, 19, "fire", "", 5, 4, 0)); monsterList[i].SetAttacks(new int[6] { 3, 12, 0, 3, 12, 0 });
        i = 91; monsterList.Add(new MonsterStack(i, "CONEHEAD", "CONEHEADS", "THE HIGH MASTER", "HIGH MASTERS", 1, 1, 15, 4, 0, MonsterStack.Class.Fighter, -2, 0, 0, 0, 3000, 9, 19, "fire cold arcane", "crit", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 3, 12, 0, 3, 12, 0, 3, 6, 0 });
        i = 92; monsterList.Add(new MonsterStack(i, "STRANGE ANIMAL", "STRANGE ANIMALS", "FLACK", "FLECK", 1, 1, 15, 12, 0, MonsterStack.Class.Animal, -3, 1, 0, 0, 9200, 9, 19, "physical fire cold arcane", "stone poison para crit", 0, 0, 0)); monsterList[i].SetAttacks(new int[3] { 4, 8, 3 });
        i = 93; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "ARCH MAGE", "ARCH MAGES", 1, 1, 20, 4, 0, MonsterStack.Class.Mage, 0, 0, 0, 0, 3160, 9, 19, "", "", 6, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 94; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "MAELIFIC", "MAELIFICS", 2, 2, 25, 4, 0, MonsterStack.Class.Undead, -5, 0, 3, 3, 7460, 9, 19, "", "poison para", 7, 0, 50)); monsterList[i].SetAttacks(new int[6] { 1, 4, 0, 1, 1, 1 });
        i = 95; monsterList.Add(new MonsterStack(i, "UNSEEN ENTITY", "UNSEEN ENTITIES", "VAMPIRE LORD", "VAMPIRE LORDS", 1, 1, 20, 8, 0, MonsterStack.Class.Undead, -5, 0, 4, 4, 7320, 9, 19, "", "para", 6, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 96; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MAN IN ROBES", "*W*E*R*D*N*A*", "*W*E*R*D*N*A*", 1, 1, 10, 10, 20, MonsterStack.Class.Mage, -7, 0, 4, 5, 15880, 20, 20, "fire cold", "stone poison para crit", 7, 7, 70)); monsterList[i].SetAttacks(new int[6] { 8, 5, 0, 8, 5, 0 });
        i = 97; monsterList.Add(new MonsterStack(i, "MAN IN KIMONO", "MEN IN KIMONOS", "HIGH NINJA", "HIGH NINJAS", 2, 2, 12, 4, 0, MonsterStack.Class.Fighter, -1, 0, 0, 0, 1600, 0, 0, "", "crit", 0, 0, 0)); monsterList[i].SetAttacks(new int[9] { 3, 81, 0, 3, 8, 0, 3, 8, 0 });
        i = 98; monsterList.Add(new MonsterStack(i, "PRIEST", "PRIESTS", "HIGH PRIEST", "HIGH PRIESTS", 2, 2, 8, 8, 0, MonsterStack.Class.Priest, 2, 0, 0, 0, 22000, 0, 0, "", "", 0, 5, 0)); monsterList[i].SetAttacks(new int[3] { 1, 8, 4 });
        i = 99; monsterList.Add(new MonsterStack(i, "MAN IN ROBES", "MEN IN ROBES", "LVL7 MAGE", "LVL7 MAGES", 2, 2, 7, 4, 0, MonsterStack.Class.Mage, 8, 0, 0, 0, 100, 0, 0, "", "sleep", 4, 0, 0)); monsterList[i].SetAttacks(new int[3] { 1, 4, 0 });
        i = 100; monsterList.Add(new MonsterStack(i, "MAN IN ARMOR", "MEN IN ROBES", "LVL7 FIGHTER", "LVL7 FIGHTERS", 2, 2, 7, 10, 0, MonsterStack.Class.Fighter, 0, 0, 0, 0, 1900, 21, 21, "", "", 0, 0, 0)); monsterList[i].SetAttacks(new int[6] { 1, 12, 0, 1, 12, 0 });

        //monster buddies
         monsterList[0].SetBuddy(1, "ORC", 10);
         monsterList[1].SetBuddy(2, "KOBOLD", 20);
         monsterList[2].SetBuddy(1, "ORC", 15);
         monsterList[3].SetBuddy(2, "KOPBOLD", 10);
         monsterList[4].SetBuddy(1, "ORC", 20);
         monsterList[5].SetBuddy(7, "ZOMBIE", 20);
         monsterList[6].SetBuddy(7, "ZOMBIE", 20);
         monsterList[7].SetBuddy(8, "CREEPING CRUD", 20);
         monsterList[8].SetBuddy(0, "BUBBLY SLIME", 24);
         monsterList[9].SetBuddy(0, "BUBBLY SLIME", 15);
        monsterList[10].SetBuddy(6, "HIGHWAYMAN", 20);
        monsterList[11].SetBuddy(4, "ROGUE", 25);
        monsterList[12].SetBuddy(12, "CREEPING COIN?", 100);
        monsterList[13].SetBuddy(13, "LVL1 NINJA", 20);
        monsterList[14].SetBuddy(15, "CAPYBARA", 20);
        monsterList[15].SetBuddy(17, "COYOTE", 20);
        monsterList[16].SetBuddy(17, "COYOTE", 20);
        monsterList[17].SetBuddy(14, "VORPAL BUNNY", 25);
        monsterList[18].SetBuddy(11, "LVL1 PRIEST", 30);
        monsterList[19].SetBuddy(12, "CREEPING COIN?", 20);
        monsterList[20].SetBuddy(13, "LVL1 NINJA", 20);
        monsterList[21].SetBuddy(14, "VORPAL BUNNY", 30);
        monsterList[22].SetBuddy(22, "", 0);
        monsterList[23].SetBuddy(34, "GRAVE MIST", 10);
        monsterList[24].SetBuddy(14, "VORPAL BUNNY", 20);
        monsterList[25].SetBuddy(27, "BORING BEETLE", 10);
        monsterList[26].SetBuddy(17, "COYOTE", 50);
        monsterList[27].SetBuddy(31, "HUGE SPIDER", 20);
        monsterList[28].SetBuddy(22, "DRAGON FLY", 40);
        monsterList[29].SetBuddy(28, "GAS DRAGON", 60);
        monsterList[30].SetBuddy(32, "ATTACK DOG", 35);
        monsterList[31].SetBuddy(37, "SHADE", 10);
        monsterList[32].SetBuddy(22, "DRAGON FLY", 20);
        monsterList[33].SetBuddy(33, "", 0);
        monsterList[34].SetBuddy(37, "SHADE", 20);
        monsterList[35].SetBuddy(26, "WERERAT", 10);
        monsterList[36].SetBuddy(26, "WERERAT", 25);
        monsterList[37].SetBuddy(23, "ROTTING CORPSE", 20);
        monsterList[38].SetBuddy(39, "MINOR DAIMYO", 10);
        monsterList[39].SetBuddy(38, "BISHOP", 20);
        monsterList[40].SetBuddy(41, "LVL4 THIEF", 20);
        monsterList[41].SetBuddy(38, "BISHOP", 20);
        monsterList[42].SetBuddy(35, "DRAGON PUPPY", 15);
        monsterList[43].SetBuddy(33, "GARGOYLE", 20);
        monsterList[44].SetBuddy(31, "HUGE SPIDER", 20);
        monsterList[45].SetBuddy(36, "WEREWOLF", 20);
        monsterList[46].SetBuddy(43, "SPIRIT", 20);
        monsterList[47].SetBuddy(48, "LVL6 NINJA", 20);
        monsterList[48].SetBuddy(50, "MASTER THIEF", 20);
        monsterList[49].SetBuddy(48, "LVL6 NINJA", 20);
        monsterList[50].SetBuddy(47, "LVL5 PRIEST", 10);
        monsterList[51].SetBuddy(47, "LVL5 PRIEST", 50);
        monsterList[52].SetBuddy(53, "CHAMPION SAMURAI", 20);
        monsterList[53].SetBuddy(52, "HIGH PRIEST", 25);
        monsterList[54].SetBuddy(53, "CHAMPION SAMURAI", 30);
        monsterList[55].SetBuddy(54, "ARCH MAGE", 25);
        monsterList[56].SetBuddy(56, "GAZE HOUND", 20);
        monsterList[57].SetBuddy(58, "TROLL", 10);
        monsterList[58].SetBuddy(58, "TROLL", 5);
        monsterList[59].SetBuddy(59, "LIFESTEALER", 50);
        monsterList[60].SetBuddy(57, "OGRE LORD", 23);
        monsterList[61].SetBuddy(43, "SPIRIT", 20);
        monsterList[62].SetBuddy(61, "WYVERN", 20);
        monsterList[63].SetBuddy(63, "LVL10 FIGHTER", 10);
        monsterList[64].SetBuddy(61, "WYVERN", 30);
        monsterList[65].SetBuddy(62, "LVL8 PRIEST", 20);
        monsterList[66].SetBuddy(60, "NIGHTSTALKER", 20);
        monsterList[67].SetBuddy(67, "", 0);
        monsterList[68].SetBuddy(66, "LVL8 NINJA", 80);
        monsterList[69].SetBuddy(54, "ARCH MAGE", 20);
        monsterList[70].SetBuddy(68, "LESSER DEOMON", 10);
        monsterList[71].SetBuddy(69, "CHIMERA", 50); //NICE
        monsterList[72].SetBuddy(71, "GORGON", 20);
        monsterList[73].SetBuddy(73, "LVL8 FIGHTER", 20);
        monsterList[74].SetBuddy(71, "GORGON", 30);
        monsterList[75].SetBuddy(71, "GORGON", 20);
        monsterList[76].SetBuddy(64, "LVL7 MAGE", 30);
        monsterList[77].SetBuddy(77, "MURPHY'S GHOST", 80);
        monsterList[78].SetBuddy(78, "", 0);
        monsterList[79].SetBuddy(76, "MASTER NINJA", 20);
        monsterList[80].SetBuddy(75, "THIEF", 30);
        monsterList[81].SetBuddy(81, "", 0);
        monsterList[82].SetBuddy(70, "FIRE GIANT", 100);
        monsterList[83].SetBuddy(72, "LVL8 BISHOP", 100);
        monsterList[84].SetBuddy(73, "LVL8 FIGHTER", 100);
        monsterList[85].SetBuddy(74, "LAVL10 MAGE", 100);
        monsterList[86].SetBuddy(86, "VAMPIRE", 15);
        monsterList[87].SetBuddy(66, "LVL8 NINJA", 70);
        monsterList[88].SetBuddy(78, "WILL O' WISP", 50);
        monsterList[89].SetBuddy(79, "BLEEB", 10);
        monsterList[90].SetBuddy(82, "HIGH PRIEST", 100);
        monsterList[91].SetBuddy(85, "HATAMOTO", 100);
        monsterList[92].SetBuddy(77, "MURPHY'S GHOST", 100);
        monsterList[93].SetBuddy(83, "HIGH WIZARD", 100);
        monsterList[94].SetBuddy(88, "POISON GIANT", 100);
        monsterList[95].SetBuddy(86, "VAMPIRE", 100);
        monsterList[96].SetBuddy(95, "VAMPIRE LORD", 100);
        monsterList[97].SetBuddy(97, "", 0);
        monsterList[98].SetBuddy(97, "HIGH NINJA", 100);
        monsterList[99].SetBuddy(98, "HIGH PRIEST", 100);
       monsterList[100].SetBuddy(99, "LVL7 MAGE", 100);
    }


}
